set -o vi
set bell-style none

alias less="less -i"

export TERM=xterm
export EDITOR=/usr/bin/bin
export TZ="Europe/Berlin"

# set PATH to include user's private bin if it exists and is not alread included
if ( echo $PATH | grep -vq "$HOME/bin" ) && [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
